name: Autograding Tests
on:
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest    
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'    
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Checkout code
      uses: actions/checkout@v4
    - name: py_5a_ej5a1_test
      id: py_5a_ej5a1_test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: py_5a_ej5a1_test
        setup-command: sudo -H pip install -r requirements.txt
        command: pytest 5a/ej5a1_test.py
        timeout: 10
        max-score: 1
    - name: py_5a_ej5a2_test
      id: py_5a_ej5a2_test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: py_5a_ej5a2_test
        setup-command: sudo -H pip install -r requirements.txt
        command: pytest 5a/ej5a2_test.py
        timeout: 10
        max-score: 1
    - name: py_5a_ej5a3_test
      id: py_5a_ej5a3_test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: py_5a_ej5a3_test
        setup-command: sudo -H pip install -r requirements.txt
        command: pytest 5a/ej5a3_test.py
        timeout: 10
        max-score: 1
    - name: py_5a_ej5a4_test
      id: py_5a_ej5a4_test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: py_5a_ej5a4_test
        setup-command: sudo -H pip install -r requirements.txt
        command: pytest 5a/ej5a4_test.py
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PY_5A_EJ5A1_TEST_RESULTS: "${{steps.py_5a_ej5a1_test.outputs.result}}"
        PY_5A_EJ5A2_TEST_RESULTS: "${{steps.py_5a_ej5a2_test.outputs.result}}"
        PY_5A_EJ5A3_TEST_RESULTS: "${{steps.py_5a_ej5a3_test.outputs.result}}"
        PY_5A_EJ5A4_TEST_RESULTS: "${{steps.py_5a_ej5a4_test.outputs.result}}"
      with:
        runners: py_5a_ej5a1_test,py_5a_ej5a2_test,py_5a_ej5a3_test,py_5a_ej5a4_test
